#Tests Generated by ChatGPT
from tests import *
from backend.database.postgres import *

class TestGetDbConnection(TestCase):

    @patch('backend.database.postgres.psycopg2.connect')
    def test_get_db_connection_success(self, mock_connect):
        # Mock environment variables
        with patch.dict(os.environ, {
            'DB_NAME': 'test_db',
            'DB_USER': 'test_user',
            'DB_PASSWORD': 'test_password',
            'DB_HOST': 'localhost',
            'DB_PORT': '5432'
        }):
            # Mock the psycopg2 connection
            mock_conn = MagicMock()
            mock_connect.return_value = mock_conn

            # Call the function under test
            conn = get_db_connection()

            # Assertions to verify the function's behavior
            self.assertIsNotNone(conn)
            mock_connect.assert_called_once_with(
                dbname='test_db',
                user='test_user',
                password='test_password',
                host='localhost',
                port=5432
            )

    @patch('backend.database.postgres.psycopg2.connect')
    def test_get_db_connection_exception(self, mock_connect):
        # Mock environment variables
        with patch.dict(os.environ, {
            'DB_NAME': 'test_db',
            'DB_USER': 'test_user',
            'DB_PASSWORD': 'test_password',
            'DB_HOST': 'localhost',
            'DB_PORT': '5432'
        }):
            # Configure the mock to raise an exception
            mock_connect.side_effect = Exception('Database connection failed')

            # Call the function under test and assert it raises an exception
            with self.assertRaises(Exception) as context:
                get_db_connection()

            self.assertIn('Database connection failed', str(context.exception))
            mock_connect.assert_called_once()

    @patch('backend.database.postgres.psycopg2.connect')
    def test_get_db_connection_missing_env_vars(self, mock_connect):
        # Clear environment variables
        with patch.dict(os.environ, {}, clear=True):
            # Call the function under test and expect it to raise a KeyError or TypeError
            with self.assertRaises(Exception) as context:
                get_db_connection()

            # Ensure that psycopg2.connect was not called due to missing env vars
            mock_connect.assert_not_called()

    @patch('backend.database.postgres.psycopg2.connect')
    def test_get_db_connection_invalid_port(self, mock_connect):
        # Mock environment variables with invalid port
        with patch.dict(os.environ, {
            'DB_NAME': 'test_db',
            'DB_USER': 'test_user',
            'DB_PASSWORD': 'test_password',
            'DB_HOST': 'localhost',
            'DB_PORT': 'invalid_port'  # Invalid port
        }):
            # Call the function under test and expect it to raise a ValueError
            with self.assertRaises(ValueError) as context:
                get_db_connection()

            self.assertIn("invalid literal for int()", str(context.exception))
            mock_connect.assert_not_called()

class TestUserConversations(TestCase):

    # ------------------------------------------------------------------
    # Tests for create_user_conversation
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_conversation_success(self, mock_get_db_connection):
        """Test successfully creating a user_conversation."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Mock fetchone to return a newly generated conversation_id (UUID)
        mock_cursor.fetchone.return_value = ['123e4567-e89b-12d3-a456-426614174000']

        # Call the function under test
        conv_id = create_user_conversation('course-uuid-123','user-uuid-456', 'gpt-4o', 'My Conversation')

        # Assertions
        self.assertEqual(conv_id, '123e4567-e89b-12d3-a456-426614174000')
        mock_get_db_connection.assert_called_once()

        expected_query = """
            INSERT INTO user_conversations (course_id, user_id, model, title)
            VALUES (%s, %s, %s, %s)
            RETURNING conversation_id;
        """
        mock_cursor.execute.assert_called_once_with(
            expected_query, ('courseuuid123', 'useruuid456', 'gpt-4o', 'My Conversation')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_conversation_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for create_user_conversation."""
        mock_get_db_connection.return_value = None

        conv_id = create_user_conversation('course-uuid-123', 'user-uuid-456', 'gpt-4o', 'Some Title')
        self.assertIsNone(conv_id)

        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_conversation_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception on execute for create_user_conversation."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Insert error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        conv_id = create_user_conversation('course-uuid-123', 'user-uuid-456', 'gpt-4o', 'Another Title')
        self.assertIsNone(conv_id)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error creating user conversation: Insert error")

    # ------------------------------------------------------------------
    # Tests for read_conversations_by_user
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_conversations_by_user_success(self, mock_get_db_connection):
        """Test returning conversation IDs for a given user and course."""
        mock_rows = [
            {'conversation_id': 'conv-uuid-111'},
            {'conversation_id': 'conv-uuid-222'}
        ]

        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchall.return_value = mock_rows
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        conversations = read_conversations_by_user('user-uuid-456', 'course-uuid-999')
        i = 0
        for conversation in conversations:
            self.assertEqual(conversation.conversation_id, mock_rows[i]['conversation_id'])

        mock_get_db_connection.assert_called_once()
        select_query = "SELECT * FROM user_conversations WHERE user_id = %s AND course_id = %s;"
        mock_cursor.execute.assert_called_once_with(select_query, ('useruuid456', 'courseuuid999'))
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_conversations_by_user_no_result(self, mock_get_db_connection):
        """Test returning an empty list when no conversation is found."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchall.return_value = []
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_conversations_by_user('user-uuid-789', 'course-uuid-999')
        self.assertEqual(result, [])

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_conversations_by_user_exception(self, mock_get_db_connection, mock_log_error):
        """Test returning an empty list upon exception."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Select error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_conversations_by_user('user-uuid-456', 'course-uuid-999')
        self.assertEqual(result, [])
        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving conversation ids: Select error")

    # ------------------------------------------------------------------
    # Tests for update_conversation_title
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_update_conversation_title_success(self, mock_get_db_connection):
        """Test updating the conversation title successfully (by conversation_id only)."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_conversation_title('conv-uuid-123', 'Updated Title')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "UPDATE user_conversations SET title = %s WHERE conversation_id = %s;",
            ('Updated Title', 'conv-uuid-123')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_conversation_title_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test db connection failure scenario for update_conversation_title."""
        mock_get_db_connection.return_value = None

        result = update_conversation_title('conv-uuid-123', 'New Title')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_conversation_title_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for update_conversation_title."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Update error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_conversation_title('conv-uuid-234', 'Another Title')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error updating conversation title: Update error")

    # ------------------------------------------------------------------
    # Tests for delete_conversation
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_conversation_success(self, mock_get_db_connection):
        """Test successfully deleting a conversation by conversation_id."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_conversation('conv-uuid-999')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "DELETE FROM user_conversations WHERE conversation_id = %s;", 
            ('conv-uuid-999',)
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_conversation_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for delete_conversation."""
        mock_get_db_connection.return_value = None

        result = delete_conversation('conv-uuid-999')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_conversation_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for delete_conversation."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Delete error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_conversation('conv-uuid-999')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error deleting conversation: Delete error")

class TestCourses(TestCase):

    # ------------------------------------------------------------------
    # Tests for create_course
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_create_course_success(self, mock_get_db_connection):
        """Test creating a course successfully."""
        # Mock the database connection and cursor
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Simulate returning a new UUID from RETURNING id;
        mock_cursor.fetchone.return_value = ['123e4567-e89b-12d3-a456-426614174000']

        # Call the function under test
        course_id = create_course(
            instructor_id="instructor-uuid-1",
            display_name="Intro to Chemistry",
            subject="CHEM",
            course_number=101,
            section_number=1,
            title="Chemistry Basics",
            model="some_model",
            prompt="Welcome to Chemistry!",
            documents_path="/chem/docs",
            image_path="/chem/image.png"
        )

        # Assertions
        self.assertEqual(course_id, '123e4567-e89b-12d3-a456-426614174000')
        mock_get_db_connection.assert_called_once()

        # Verify the query and parameters
        expected_query = """
            INSERT INTO courses (instructor_id, display_name, subject, course_number, section_number, title, model, prompt, documents_path, image_path)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id;
        """
        mock_cursor.execute.assert_called_once_with(
            expected_query,
            (
                "instructor-uuid-1",
                "Intro to Chemistry",
                "CHEM",
                101,
                1,
                "Chemistry Basics",
                "some_model",
                "Welcome to Chemistry!",
                "/chem/docs",
                "/chem/image.png"
            )
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_course_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for create_course."""
        mock_get_db_connection.return_value = None

        # Call the function under test
        course_id = create_course(
            instructor_id="instructor-uuid-2",
            display_name="Intro to Biology",
            subject="BIOL",
            course_number=200,
            section_number=2,
            title="Biology 200",
            model="some_model",
            prompt="Welcome to Biology",
            documents_path="/bio/docs",
            image_path="/bio/image.png"
        )

        # Assertions
        self.assertIsNone(course_id)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_course_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario during course creation."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_cursor.execute.side_effect = Exception('Database error')
        mock_get_db_connection.return_value = mock_conn

        course_id = create_course(
            instructor_id="instructor-uuid-3",
            display_name="Intro to Physics",
            subject="PHYS",
            course_number=300,
            section_number=3,
            title="Physics 300",
            model="another_model",
            prompt="Welcome to Physics!",
            documents_path="/phys/docs",
            image_path="/phys/image.png"
        )

        self.assertIsNone(course_id)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error creating course: Database error")

    # ------------------------------------------------------------------
    # Tests for read_course_by_id
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_course_by_id_success(self, mock_get_db_connection):
        """Test retrieving course by ID successfully."""
        mock_course = {
            'id': '123e4567-e89b-12d3-a456-426614174000',
            'instructor_id': 'instructor-uuid-1',
            'display_name': 'Intro to Chemistry',
            'subject': 'CHEM',
            'course_number': 101,
            'section_number': 1,
            'title': 'Chemistry Basics',
            'model': 'some_model',
            'prompt': 'Welcome to Chemistry!',
            'documents_path': '/chem/docs',
            'image_path': '/chem/image.png',
            'created_at': None,
            'archived': False,
            'archived_by': None,
            'archived_at': None
        }

        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = mock_course
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_course_by_id('123e4567-e89b-12d3-a456-426614174000')
        self.assertEqual(result, mock_course)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "SELECT * FROM courses WHERE id = %s;", 
            ('123e4567-e89b-12d3-a456-426614174000',)
        )
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_course_by_id_no_course_found(self, mock_get_db_connection):
        """Test returning None when no course is found by ID."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = None
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_course_by_id('nonexistent-uuid')
        self.assertIsNone(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_course_by_id_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for read_course_by_id."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Query error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_course_by_id('some-uuid')
        self.assertIsNone(result)
        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving course info: Query error")

    # ------------------------------------------------------------------
    # Tests for update_course_title
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_title_success(self, mock_get_db_connection):
        """Test updating course title successfully."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_course_title('123e4567-e89b-12d3-a456-426614174000', 'New Title')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            """ UPDATE courses SET title = %s WHERE id = %s; """,
            ('New Title', '123e4567-e89b-12d3-a456-426614174000')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_title_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test db connection failure scenario for update_course_title."""
        mock_get_db_connection.return_value = None

        result = update_course_title('some-uuid', 'Another Title')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()

        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_title_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for update_course_title."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Update error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_course_title('some-uuid', 'Another Title')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error updating course title: Update error")

    # ------------------------------------------------------------------
    # Tests for update_course_model
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_model_success(self, mock_get_db_connection):
        """Test updating course model successfully."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_course_model('123e4567-e89b-12d3-a456-426614174000', 'new_model')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            """ UPDATE courses SET model = %s WHERE id = %s; """,
            ('new_model', '123e4567-e89b-12d3-a456-426614174000')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_model_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test db connection failure for update_course_model."""
        mock_get_db_connection.return_value = None

        result = update_course_model('some-uuid', 'another_model')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_course_model_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for update_course_model."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Update error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_course_model('some-uuid', 'another_model')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error updating course model: Update error")

    # ------------------------------------------------------------------
    # Tests for delete_course
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_course_success(self, mock_get_db_connection):
        """Test successfully deleting a course by ID."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_course('123e4567-e89b-12d3-a456-426614174000')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "DELETE FROM courses WHERE id = %s;",
            ('123e4567-e89b-12d3-a456-426614174000',)
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_course_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test db connection failure for delete_course."""
        mock_get_db_connection.return_value = None

        result = delete_course('some-uuid')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_course_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for delete_course."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Delete error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_course('some-uuid')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error deleting course: Delete error")

class TestMessages(TestCase):

    # ------------------------------------------------------------------
    # Tests for create_message
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_create_message_success(self, mock_get_db_connection):
        """Test successfully creating a message."""
        # Mock the database connection and cursor
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Mock the returned message ID (an integer per the schema)
        mock_cursor.fetchone.return_value = [123]

        # Call the function under test
        message_id = create_message('conv-uuid-123', 'gpt-4o', 'Hello, how are you?', 'I am good!'
        )

        # Assertions
        self.assertEqual(message_id, 123)
        mock_get_db_connection.assert_called_once()

        expected_query = """
            INSERT INTO messages (conversation_id, model, prompt, response)
            VALUES (%s, %s, %s, %s)
            RETURNING id;
        """
        mock_cursor.execute.assert_called_once_with(
            expected_query,
            ('conv-uuid-123', 'gpt-4o', 'Hello, how are you?', 'I am good!')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_message_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure scenario for create_message."""
        mock_get_db_connection.return_value = None

        message_id = create_message('conv-uuid-123', 'gpt-4o', 'Question?', 'Answer!')
        self.assertIsNone(message_id)
        mock_get_db_connection.assert_called_once()

        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_message_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario during INSERT query for create_message."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Insert error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        message_id = create_message('conv-uuid-456', 'gpt-4o', 'Prompt?', 'Response!')
        self.assertIsNone(message_id)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error adding message: Insert error")

    # ------------------------------------------------------------------
    # Tests for read_messages_from_conversation
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_messages_from_conversation_success(self, mock_get_db_connection):
        """Test retrieving messages (prompt/response) for a conversation."""
        mock_rows = [
            {'model': 'gpt-4o', 'prompt': 'Hello', 'response': 'Hi there!'},
            {'model': 'gpt-4o', 'prompt': 'How are you?', 'response': 'Doing well!'}
        ]

        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchall.return_value = mock_rows
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        messages = read_messages_from_conversation('conv-uuid-123')
        i = 0
        for message in messages:
            self.assertEqual(message.model, mock_rows[i]['model'])
            self.assertEqual(message.prompt, mock_rows[i]['prompt'])
            self.assertEqual(message.response, mock_rows[i]['response'])
            i += 1

        mock_get_db_connection.assert_called_once()
        query = """
            SELECT model, prompt, response FROM messages WHERE conversation_id = %s ORDER BY id ASC;
        """
        mock_cursor.execute.assert_called_once_with(query, ('conv-uuid-123',))
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_messages_from_conversation_no_result(self, mock_get_db_connection):
        """Test returning an empty list when no messages are found."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchall.return_value = []
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        messages = read_messages_from_conversation('conv-uuid-789')
        self.assertEqual(messages, [])
        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_messages_from_conversation_exception(self, mock_get_db_connection, mock_log_error):
        """Test returning an empty list upon exception."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Select error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        messages = []
        try:
            messages = read_messages_from_conversation('conv-uuid-123')
        except HTTPError as e:
            pass # We are not testing this error in this test case
        
        self.assertEqual(messages, [])
        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving messages: Select error")

class TestUserCourses(TestCase):

    # ------------------------------------------------------------------
    # Tests for create_user_course
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_course_success(self, mock_get_db_connection):
        """
        Test a successful insertion into user_courses.
        rowcount == 1 indicates a new row was inserted.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Simulate rowcount = 1 => new record was inserted
        mock_cursor.rowcount = 1

        result = create_user_course('course-uuid-123', 'user-uuid-456')
        self.assertTrue(result)
        mock_get_db_connection.assert_called_once()

        insert_query = """
            INSERT INTO user_courses (course_id, user_id)
            VALUES (%s, %s)
            ON CONFLICT (course_id, user_id) DO NOTHING
        """
        mock_cursor.execute.assert_called_once_with(
            insert_query,
            ('course-uuid-123', 'user-uuid-456')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_course_conflict(self, mock_get_db_connection):
        """
        Test the scenario where the record already exists, causing rowcount == 0.
        This should return False since no new record was inserted.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # rowcount = 0 => conflict or already exists => no new insertion
        mock_cursor.rowcount = 0

        result = create_user_course('course-uuid-123', 'user-uuid-456')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_course_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for create_user_course."""
        mock_get_db_connection.return_value = None

        result = create_user_course('course-uuid-123', 'user-uuid-456')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()

        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_course_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario during insertion."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Insert error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = create_user_course('course-uuid-123', 'user-uuid-456')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error creating user course: Insert error")

    # ------------------------------------------------------------------
    # Tests for read_users_for_course
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_users_for_course_success(self, mock_get_db_connection):
        """
        Test returning user IDs for a course. Should return a list of user_id strings.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()

        # Suppose we have two rows with 'user_id' keys
        mock_cursor.fetchall.return_value = [
            {'user_id': 'user-uuid-111'},
            {'user_id': 'user-uuid-222'}
        ]
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        user_ids = read_users_for_course('course-uuid-123')
        self.assertEqual(user_ids, ['user-uuid-111', 'user-uuid-222'])

        mock_get_db_connection.assert_called_once()
        select_query = """
            SELECT user_id FROM user_courses WHERE course_id = %s;
        """
        mock_cursor.execute.assert_called_once_with(select_query, ('course-uuid-123',))
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_users_for_course_no_result(self, mock_get_db_connection):
        """
        Test returning an empty list when no user is found for the course.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchall.return_value = []
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        user_ids = read_users_for_course('course-uuid-999')
        self.assertEqual(user_ids, [])

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_users_for_course_exception(self, mock_get_db_connection, mock_log_error):
        """
        Test returning an empty list upon exception.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Select error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        user_ids = read_users_for_course('course-uuid-888')
        self.assertEqual(user_ids, [])
        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving users for course course-uuid-888: Select error")

    # ------------------------------------------------------------------
    # Tests for delete_user_course
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_course_success(self, mock_get_db_connection):
        """
        Test deleting a user-course combination by course_id and user_id.
        """
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user_course('course-uuid-123', 'user-uuid-456')
        self.assertTrue(result)
        mock_get_db_connection.assert_called_once()

        delete_query = """
            DELETE FROM user_courses WHERE course_id = %s AND user_id = %s;
        """
        mock_cursor.execute.assert_called_once_with(delete_query, ('course-uuid-123', 'user-uuid-456'))
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_course_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for delete_user_course."""
        mock_get_db_connection.return_value = None

        result = delete_user_course('course-uuid-111', 'user-uuid-999')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_course_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for delete_user_course."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Delete error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user_course('course-uuid-111', 'user-uuid-999')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error deleting user course: Delete error")

    # ------------------------------------------------------------------
    # Tests for delete_user_courses_by_course (new method)
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_courses_by_course_success(self, mock_get_db_connection):
        """Test deleting all user-course associations for a given course."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user_courses_by_course('course-uuid-123')
        self.assertTrue(result)
        mock_get_db_connection.assert_called_once()

        delete_query = """
            DELETE FROM user_courses WHERE course_id = %s;
        """
        mock_cursor.execute.assert_called_once_with(delete_query, ('course-uuid-123',))
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_courses_by_course_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for delete_user_courses_by_course."""
        mock_get_db_connection.return_value = None

        result = delete_user_courses_by_course('course-uuid-999')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_courses_by_course_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for delete_user_courses_by_course."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Delete error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user_courses_by_course('course-uuid-999')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error deleting user courses by course_id 'course-uuid-999': Delete error")

class TestUsers(TestCase):

    # ------------------------------------------------------------------
    # Tests for create_user
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_success(self, mock_get_db_connection):
        """Test creating a user successfully."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = create_user(display_name='Alice', email='alice@example.com', role='professor')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()

        expected_query = """
            INSERT INTO users (id, display_name, email, role)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (email) DO NOTHING;
        """
        mock_cursor.execute.assert_called_once_with(
            expected_query,
            (ANY, 'Alice', 'alice@example.com', 'professor')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test when get_db_connection returns None."""
        mock_get_db_connection.return_value = None

        result = create_user('Bob', 'bob@example.com')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_create_user_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception during INSERT query."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Database error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = create_user('Charlie', 'charlie@example.com', 'student')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error inserting user: Database error")

    # ------------------------------------------------------------------
    # Tests for read_user_by_id
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_id_success(self, mock_get_db_connection):
        """Test retrieving user info (display_name, role) by ID."""
        mock_row = {'display_name': 'Alice', 'role': 'student'}
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = mock_row
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_id('some-uuid-123')
        self.assertEqual(result, mock_row)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "SELECT id, email, display_name, role FROM users WHERE id = %s;", 
            ('some-uuid-123',)
        )
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_id_no_user(self, mock_get_db_connection):
        """Test returning None if no user found."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = None
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_id('nonexistent-uuid')
        self.assertIsNone(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_id_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception handling for read_user_by_id."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Query error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_id('some-uuid-123')
        self.assertIsNone(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving user: Query error")

    # ------------------------------------------------------------------
    # Tests for read_user_by_email
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_email_success(self, mock_get_db_connection):
        """Test retrieving user info (id, email, display_name, role) by email."""
        mock_row = {'id': str(uuid.uuid4()), 'email': 'bob@example.com', 'display_name': 'Bob', 'role': 'student'}
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = mock_row
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_email('bob@example.com')
        self.assertEqual(result.email, mock_row['email'])
        self.assertEqual(result.display_name, mock_row['display_name'])
        self.assertEqual(result.role.name, mock_row['role'])
        self.assertIsInstance(result.id, uuid.UUID)


        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "SELECT id, display_name, email, role FROM users WHERE email = %s;",
            ('bob@example.com',)
        )
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_email_no_user(self, mock_get_db_connection):
        """Test returning None if no user found by email."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = None
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_email('unknown@example.com')
        self.assertIsNone(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_user_by_email_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception when reading user by email."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Query error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = read_user_by_email('charlie@example.com')
        self.assertIsNone(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving user by email: Query error")

    # ------------------------------------------------------------------
    # Tests for read_email_by_id
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_read_email_by_id_success(self, mock_get_db_connection):
        """Test retrieving email by user ID."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = {'email': 'alice@example.com'}
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        email = read_email_by_id('some-uuid-123')
        self.assertEqual(email, 'alice@example.com')

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "SELECT email FROM users WHERE id = %s;", 
            ('some-uuid-123',)
        )
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.get_db_connection')
    def test_read_email_by_id_no_user(self, mock_get_db_connection):
        """Test returning None if no user found by ID when reading email."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.fetchone.return_value = None
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        email = read_email_by_id('nonexistent-uuid')
        self.assertIsNone(email)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_read_email_by_id_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception when reading email by ID."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Query error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        email = read_email_by_id('some-uuid-123')
        self.assertIsNone(email)

        mock_get_db_connection.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error retrieving user email by ID: Query error")

    # ------------------------------------------------------------------
    # Tests for update_user_display_name
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_update_user_display_name_success(self, mock_get_db_connection):
        """Test updating user's display name by email, success scenario."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_user_display_name('NewName', 'alice@example.com')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "UPDATE users SET display_name = %s WHERE email = %s;",
            ('NewName', 'alice@example.com')
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_user_display_name_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure for update_user_display_name."""
        mock_get_db_connection.return_value = None

    
        result = update_user_display_name('AnotherName', 'bob@example.com')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_update_user_display_name_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for update_user_display_name."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Update error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = update_user_display_name('AnotherName', 'bob@example.com')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error updating user display name: Update error")

    # ------------------------------------------------------------------
    # Tests for delete_user
    # ------------------------------------------------------------------
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_success(self, mock_get_db_connection):
        """Test successful delete of user by ID."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user('some-uuid-123')
        self.assertTrue(result)

        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once_with(
            "DELETE FROM users WHERE id = %s;", 
            ('some-uuid-123',)
        )
        mock_conn.commit.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_db_connection_failure(self, mock_get_db_connection, mock_log_error):
        """Test DB connection failure scenario for delete_user."""
        mock_get_db_connection.return_value = None

        result = delete_user('some-uuid-123')
        self.assertFalse(result)
        mock_get_db_connection.assert_called_once()
        mock_log_error.assert_called_once_with("Failed to connect to the database.")

    @patch('backend.database.postgres.logging.error')
    @patch('backend.database.postgres.get_db_connection')
    def test_delete_user_exception(self, mock_get_db_connection, mock_log_error):
        """Test exception scenario for delete_user."""
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.execute.side_effect = Exception('Delete error')
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        result = delete_user('some-uuid-123')
        self.assertFalse(result)

        mock_get_db_connection.assert_called_once()
        mock_conn.rollback.assert_called_once()
        mock_cursor.close.assert_called_once()
        mock_conn.close.assert_called_once()

        mock_log_error.assert_called_once_with("Error deleting user: Delete error")


if __name__ == '__main__':
    main()