#Tests Generated by ChatGPT
import unittest
from unittest.mock import patch, MagicMock
import logging

# Import the function under test
from backend.database.vectorInsert import insert_embeddings_into_db

class TestInsertEmbeddingsIntoDb(unittest.TestCase):

    @patch('backend.database.vectorInsert.get_db_connection')
    @patch('backend.database.vectorInsert.embeddings_generator.get_embeddings')
    def test_insert_embeddings_success(self, mock_get_embeddings, mock_get_db_connection):
        # Sample input data
        text_chunks = ['Sample text 1', 'Sample text 2', 'Sample text 3']

        # Mock the embeddings returned by get_embeddings
        mock_get_embeddings.return_value = [
            {'text': 'Sample text 1', 'embedding': [0.1, 0.2, 0.3]},
            {'text': 'Sample text 2', 'embedding': [0.4, 0.5, 0.6]},
            {'text': 'Sample text 3', 'embedding': [0.7, 0.8, 0.9]}
        ]

        # Mock the database connection and cursor
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Call the function under test
        insert_embeddings_into_db(text_chunks)

        # Assertions to verify the function's behavior
        mock_get_embeddings.assert_called_once_with(text_chunks)
        mock_get_db_connection.assert_called_once()
        mock_conn.cursor.assert_called_once()
        self.assertEqual(mock_cursor.execute.call_count, 3)
        self.assertEqual(mock_cursor.close.call_count, 1)
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()

        # Check that execute was called with the correct parameters
        expected_calls = [
            ((("""
                INSERT INTO course_materials (title, content, embedding)
                VALUES (%s, %s, %s)
            """), (f"Insert {idx + 1}", item['text'], item['embedding'])),)
            for idx, item in enumerate(mock_get_embeddings.return_value)
        ]
        mock_cursor.execute.assert_has_calls(expected_calls, any_order=False)

    @patch('backend.database.vectorInsert.logging')
    @patch('backend.database.vectorInsert.get_db_connection')
    @patch('backend.database.vectorInsert.get_embeddings')
    def test_insert_embeddings_embedding_failure(self, mock_get_embeddings, mock_get_db_connection, mock_logging):
        # Sample input data
        text_chunks = ['Sample text 1']

        # Mock the embeddings returned by get_embeddings with None embedding
        mock_get_embeddings.return_value = [
            {'text': 'Sample text 1', 'embedding': None}
        ]

        # Mock the database connection and cursor
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Call the function under test
        insert_embeddings_into_db(text_chunks)

        # Assertions
        mock_get_embeddings.assert_called_once_with(text_chunks)
        mock_get_db_connection.assert_called_once()
        mock_logging.error.assert_called_with('Failed to get embedding for: Insert 1')

        # Ensure that execute is not called since embedding is None
        mock_cursor.execute.assert_not_called()

        # Ensure that commit and close are still called
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()
        mock_cursor.close.assert_called_once()

    @patch('backend.database.vectorInsert.logging')
    @patch('backend.database.vectorInsert.get_db_connection')
    @patch('backend.database.vectorInsert.get_embeddings')
    def test_insert_embeddings_db_connection_failure(self, mock_get_embeddings, mock_get_db_connection, mock_logging):
        # Sample input data
        text_chunks = ['Sample text 1']

        # Mock the embeddings returned by get_embeddings
        mock_get_embeddings.return_value = [
            {'text': 'Sample text 1', 'embedding': [0.1, 0.2, 0.3]}
        ]

        # Mock get_db_connection to return None
        mock_get_db_connection.return_value = None

        # Call the function under test
        insert_embeddings_into_db(text_chunks)

        # Assertions
        mock_get_embeddings.assert_called_once_with(text_chunks)
        mock_get_db_connection.assert_called_once()
        mock_logging.error.assert_called_with('Failed to connect to the database.')

        # Ensure that no further database operations are attempted
        # Since get_db_connection returns None, conn.cursor() will not be called
        # We can check that cursor methods are not called by ensuring mock_get_db_connection.return_value is None
        self.assertIsNone(mock_get_db_connection.return_value)

    @patch('backend.database.vectorInsert.logging')
    @patch('backend.database.vectorInsert.get_db_connection')
    @patch('backend.database.vectorInsert.get_embeddings')
    def test_insert_embeddings_db_insertion_error(self, mock_get_embeddings, mock_get_db_connection, mock_logging):
        # Sample input data
        text_chunks = ['Sample text 1']

        # Mock the embeddings returned by get_embeddings
        mock_get_embeddings.return_value = [
            {'text': 'Sample text 1', 'embedding': [0.1, 0.2, 0.3]}
        ]

        # Mock the database connection and cursor
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value = mock_cursor
        mock_get_db_connection.return_value = mock_conn

        # Configure cursor.execute to raise an exception
        mock_cursor.execute.side_effect = Exception('Database insertion failed')

        # Call the function under test
        insert_embeddings_into_db(text_chunks)

        # Assertions
        mock_get_embeddings.assert_called_once_with(text_chunks)
        mock_get_db_connection.assert_called_once()
        mock_cursor.execute.assert_called_once()
        mock_logging.error.assert_called_with('Database insertion error for Insert 1: Database insertion failed')

        # Ensure that commit and close are still called
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()
        mock_cursor.close.assert_called_once()

if __name__ == '__main__':
    unittest.main()